name: Build and Publish with Unity CLI

on:
  push:
    branches: [ main ]

env: 
  UGS_CLI_SERVICE_KEY_ID : ${{ secrets.UNITY_SERVICE_KEY_ID }}
  UGS_CLI_SERVICE_SECRET_KEY : ${{ secrets.UNITY_SERVICE_SECRET_KEY }}
  
  # PLEASE ENTER YOUR PROJECT INFO      
  UGS_CLI_PROJECT_ID: "133ec1d5-b4aa-40b8-878e-3e6af3f869aa"
  # PLEASE ENTER YOUR ENVIRONMENT INFO      
  UGS_CLI_ENVIRONMENT_NAME: "135a4c0f-9b3b-44a6-a3ac-666090547280"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      #- name: Download Third-Party CLI
      #  run: curl -LO https://github.com/Unity-Technologies/unity-gaming-services-cli/releases/download/v1.0.0-beta.1/ugs-linux-x64.zip

      #- name: Extract Third-Party CLI
      #  run: unzip ugs-linux-x64.zip -d cli

      - name: Publish project
        run: dotnet publish --runtime linux-x64 EndlessRunnerServer/EndlessRunnerServer.csproj --output ./publish

      - name: Zip published files
        run: zip -r publish.zip ./publish

      - name: CLI Set org
        run: cli/ugs config set organization-id ${{ secrets.UNITY_ORG_ID }}
      - name: CLI Set Project ID  
        run: cli/ugs config set project-id ${{ secrets.UNITY_PROJECT_ID }}
      - name: CLI Set Env ID
        run: cli/ugs config set environment ${{ secrets.UNITY_ENVIRONMENT_ID }}
         
      - name: CLI Publish
        run: cli/ugs cloud-code modules deploy EndlessRunnerServer ./publish.zip

      #- name: Upload zip artifact
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: publish
      #   path: ./publish/publish.zip