name: Build and Publish with Unity CLI

on:
  push:
    branches: [ main ]

env:
  UNITY_ORG_ID: ${{ secrets.UNITY_ORG_ID }}
  UNITY_PROJECT_ID: ${{ secrets.UNITY_PROJECT_ID }}
  UNITY_ENVIRONMENT_ID: ${{ secrets.UNITY_ENVIRONMENT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Download Third-Party CLI
        run: curl -LO https://github.com/Unity-Technologies/unity-gaming-services-cli/releases/download/v1.0.0-beta.1/ugs-linux-x64.zip

      - name: Extract Third-Party CLI
        run: unzip ugs-linux-x64.zip -d cli

      - name: Publish project
        run: dotnet publish --runtime linux-x64 EndlessRunnerServer/EndlessRunnerServer.csproj --output ./publish

      - name: Zip published files
        run: zip -r publish.zip publish

      - name: Execute Third-Party CLI Command with Secrets
        run: |
          cli/ugs config set organization-id ${{ env.UNITY_ORG_ID }}
          cli/ugs config set project-id ${{ env.UNITY_PROJECT_ID }}
          cli/ugs config set environment ${{ env.UNITY_ENVIRONMENT_ID }}
          cli/ugs cloud-code modules deploy EndlessRunnerServer publish/publish.zip

      - name: Upload zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: publish
          path: publish.zip